services:
  android-db:
    image: postgres:17
    ports: "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ellectionpolldb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker']
      interval: 3s
      timeout: 5s
      retries: 5